version: '3.8'

services:
  persona-generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: dylantarre/gen-persona:latest
    ports:
      - "9350:9350"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY:-default-dev-key-change-me}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9350/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
