name: Deploy to Portainer

on:
  push:
    branches: [ main ]  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up environment
        run: echo "Deploying from commit ${{ github.sha }}"
        
      - name: Trigger Portainer webhook
        run: |
          echo "Triggering Portainer webhook..."
          curl -L -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
          echo "Webhook triggered successfully" 